print("Tentativa de carregamento...")
library(devtools)
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(leaflet)
library(webshot)
library(htmlwidgets)

print("Instalando pacotes...")
install.packages("devtools")
install.packages("shiny")
install.packages("shinydashboard")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("leaflet")
install.packages("webshot")
install.packages("htmlwidgets")

print("Carregando pacotes...")
library(devtools)
library(shiny)
library(shinydashboard)
library(dplyr)
library(ggplot2)
library(leaflet)
library(webshot)
library(htmlwidgets)

print(paste("Instalando", "Geobage", "..."))
devtools::install_github("GeoInformacao/geobage")
print(paste("Carregando...", "Geobage"))
library(geobage)


print(paste("Instalando", openssl, "..."))
install.packages("httr", type = "source")
print(paste("Carregando...", openssl))
library(openssl)